### PR TITLE
Pin the AWF firewall binary to the version `gh-aw` bundles

### PR DESCRIPTION
**Pull request by dsfaccini**
> This pull request was posted by Claude Code using claude-opus-5 on behalf of David. David has not reviewed the code.

`engine.command` makes gh-aw skip its own AWF firewall install, so `shared/pre-steps.md` re-runs the installer with a version written by hand. #8041 moved gh-aw to v0.86.2, which bundles AWF **v0.27.44** and now emits `apiProxy.providers` (the `MiniMax-M3` pricing from `shared/engine-minimax.md`) into `awf-config.json`. The still-pinned **v0.27.42** binary has no such field, and its schema is `additionalProperties: false`:

```
[ERROR] Error loading --config: Invalid AWF config at .../awf-config.json:
- config.apiProxy.providers is not supported
```

Every agent job using the shim exits 1 before the model starts. It surfaced on `Pydantic AI UI Security Review`, the only agentic workflow whose `detect` job has fired since #8041 merged — [run 33816474253](https://github.com/pydantic/pydantic-ai/actions/runs/33816474253/job/100850099380). Every other workflow using `shared/pre-steps.md` is equally broken and simply has not run yet.

- Bump the pin to `v0.27.44` in all three sites (`shared/pre-steps.md`, `pydantic-ai-pr-review.md`, `pydantic-ai-stale-issues-finder.md`) and recompile with gh-aw v0.86.2 — each lock changes only its `frontmatter_hash` and the install argument.
- Add an `awf-binary-version` check to `agentic_workflow_guard.py`: the pin must equal the `GH_AW_INFO_AWF_VERSION` gh-aw compiled that lock against. Verified against the pre-fix tree — reverting one lock's pin makes it fail with the message above.
- A lock that carries a pin but declares no `GH_AW_INFO_AWF_VERSION` fails too. Returning "no violations" there is how the check would disarm itself if gh-aw ever renamed that variable, and the next skew would ship green exactly as this one did. Only a lock with no install step at all is skipped.
- Drop the duplicate AWF install from `pydantic-ai-pr-review`: it both imported `shared/pre-steps.md` and declared its own identical `pre-steps:`, so the agent job ran `install_awf_binary.sh` twice back-to-back. Every other workflow runs it once, and the shared fragment carries the same explanatory comment.

<details>
<summary>Why the pin exists at all</summary>

gh-aw installs the AWF binary itself only for engines it launches. Setting `engine.command` (the Pydantic AI MiniMax shim) makes it skip **all** engine installation steps, the firewall binary included, so `shared/pre-steps.md` re-runs `install_awf_binary.sh` by hand. `GH_AW_INFO_AWF_VERSION` is set per-step rather than at job level, so the pre-step cannot read it — hence a literal, and hence the guard.

</details>

### Checklist

- [ ] Any **AI generated code** has been reviewed line-by-line by the human PR author, who stands by it.
- [x] No **breaking changes** in accordance with the [version policy](https://github.com/pydantic/pydantic-ai/blob/main/docs/version-policy.md).
- [x] Any permitted **compatibility impact** has a label, warning, migration, release note, and exact API-check waiver.
- [x] **PR title** is fit for the [release changelog](https://github.com/pydantic/pydantic-ai/releases).

<a href="https://cubic.dev/pr/pydantic/pydantic-ai/pull/8066?utm_source=github" target="_blank" rel="noopener noreferrer" data-no-image-dialog="true"><picture><source media="(prefers-color-scheme: dark)" srcset="https://www.cubic.dev/buttons/review-in-cubic-dark.svg"><source media="(prefers-color-scheme: light)" srcset="https://www.cubic.dev/buttons/review-in-cubic-light.svg">Review in cubic</picture></a>

### CODE REVIEW

File: .github/scripts/agentic_workflow_guard.py [hunk 1]
```diff
@@ -96,6 +101,9 @@
 # wherever a prompt actually writes one.
 SANDBOX_PATH = re.compile(rf'{re.escape(SANDBOX_PREFIX)}[^\s`\'"()\[\]<>]*')
 
+# The version argument of the hand-written AWF install step, quoted or bare.
+AWF_INSTALL_VERSION = re.compile(r'install_awf_binary\.sh"?\s+(\S+)')
```
[the remark this answers is not in the document]
Comment (dsfaccini) [reply .github/scripts/agentic_workflow_guard.py]: Fixed in `607cf7e4af8e90caca598ac1b287b431bf9520f5` — the capture now stops at the quote (`"?([^"\\s]+)`), so a quoted pin compares equal. Regression test: `test_awf_binary_version_accepts_a_quoted_version`.

File: .github/scripts/agentic_workflow_guard.py [hunk 2]
```diff
@@ -437,6 +445,47 @@ def check_compiled_runner_contract(lock: Path) -> list[Violation]:
...
+    workflow = _as_mapping(yaml.safe_load(lock.read_text(encoding='utf-8')))
+    pinned: set[str] = set()
+    bundled: set[str] = set()
+    for raw_job in _as_mapping(workflow.get('jobs')).values():
+        steps = _as_mapping(raw_job).get('steps')
+        for raw_step in cast(list[Any], steps) if isinstance(steps, list) else []:
+            step = _as_mapping(raw_step)
+            run = step.get('run')
+            if isinstance(run, str) and (match := AWF_INSTALL_VERSION.search(run)):
+                pinned.add(match.group(1))
```
[the remark this answers is not in the document]
Comment (dsfaccini) [reply .github/scripts/agentic_workflow_guard.py]: Fixed in `607cf7e4af8e90caca598ac1b287b431bf9520f5` — `finditer`, since a multi-line `run` is pinned by its last invocation. Regression test: `test_awf_binary_version_reads_every_installer_invocation_in_one_step`.
