### PR TITLE
fix: LogfirePlugin compat with temporalio >= 1.23.0 (interceptors renamed)

### LINKED ISSUE #4424: LogfirePlugin doesn't work with newest Temporal
### Initial Checks

- [x] I'm using the [latest version](https://github.com/pydantic/pydantic-ai/releases/latest) of Pydantic AI
- [x] I've searched for my issue in [the issue tracker](https://github.com/pydantic/pydantic-ai/issues) before opening this issue

### Description

After upgrade of Temporal Python SDK to 1.23.0 initialization of LogfirePlugin fails with
```
temporal-worker-1                   | Starting Temporal worker...
temporal-worker-1                   |   Temporal address: temporal:7233
temporal-worker-1                   |   Temporal namespace: default
temporal-worker-1                   |   Task queue: case-processing
temporal-worker-1                   | Worker error: SimplePlugin.__init__() got an unexpected keyword argument 'client_interceptors'
temporal-worker-1                   | [25/Feb/2026 06:35:02] ERROR "apps.cases.management.commands.temporal_worker" Temporal worker error: SimplePlugin.__init__() got an unexpected keyword argument 'client_interceptors'
temporal-worker-1                   | Traceback (most recent call last):
temporal-worker-1                   |   File "/code/apps/cases/management/commands/temporal_worker.py", line 84, in run_worker
temporal-worker-1                   |     plugins=[PydanticAIPlugin(), LogfirePlugin(setup_logfire=configure_logfire)],
temporal-worker-1                   |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
temporal-worker-1                   |   File "/home/django/.venv/lib/python3.12/site-packages/pydantic_ai/durable_exec/temporal/_logfire.py", line 39, in __init__
temporal-worker-1                   |     super().__init__(  # type: ignore[reportUnknownMemberType]
temporal-worker-1                   | TypeError: SimplePlugin.__init__() got an unexpected keyword argument 'client_interceptors'
temporal-worker-1                   | Traceback (most recent call last):
temporal-worker-1                   |   File "/code/manage.py", line 15, in <module>
temporal-worker-1                   |     execute_from_command_line(sys.argv)
temporal-worker-1                   |   File "/home/django/.venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
temporal-worker-1                   |     utility.execute()
temporal-worker-1                   |   File "/home/django/.venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 437, in execute
temporal-worker-1                   |     self.fetch_command(subcommand).run_from_argv(self.argv)
temporal-worker-1                   |   File "/home/django/.venv/lib/python3.12/site-packages/django/core/management/base.py", line 420, in run_from_argv
temporal-worker-1                   |     self.execute(*args, **cmd_options)
temporal-worker-1                   |   File "/home/django/.venv/lib/python3.12/site-packages/django/core/management/base.py", line 464, in execute
temporal-worker-1                   |     output = self.handle(*args, **options)
temporal-worker-1                   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
temporal-worker-1                   |   File "/code/apps/cases/management/commands/temporal_worker.py", line 75, in handle
temporal-worker-1                   |     asyncio.run(self.run_worker(temporal_address, temporal_namespace, task_queue))
temporal-worker-1                   |   File "/usr/local/lib/python3.12/asyncio/runners.py", line 195, in run
temporal-worker-1                   |     return runner.run(main)
temporal-worker-1                   |            ^^^^^^^^^^^^^^^^
temporal-worker-1                   |   File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
temporal-worker-1                   |     return self._loop.run_until_complete(task)
temporal-worker-1                   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
temporal-worker-1                   |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
temporal-worker-1                   |     return future.result()
temporal-worker-1                   |            ^^^^^^^^^^^^^^^
temporal-worker-1                   |   File "/code/apps/cases/management/commands/temporal_worker.py", line 84, in run_worker
temporal-worker-1                   |     plugins=[PydanticAIPlugin(), LogfirePlugin(setup_logfire=configure_logfire)],
temporal-worker-1                   |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
temporal-worker-1                   |   File "/home/django/.venv/lib/python3.12/site-packages/pydantic_ai/durable_exec/temporal/_logfire.py", line 39, in __init__
temporal-worker-1                   |     super().__init__(  # type: ignore[reportUnknownMemberType]
temporal-worker-1                   | TypeError: SimplePlugin.__init__() got an unexpected keyword argument 'client_interceptors'
```

### Minimal, Reproducible Example

```Python

```

### Logfire Trace

_No response_

### Python, Pydantic AI & LLM client version

- Python: 3.12.12
- Pydantic AI: 1.63.0
- Temporal SDK: 1.23.0

### PR DESCRIPTION
**Pull request by giulio-leone**
## Summary

Fixes #4424

`LogfirePlugin` fails with `TypeError: SimplePlugin.__init__() got an unexpected keyword argument 'client_interceptors'` when using `temporalio >= 1.23.0`.

## Root Cause

In `temporalio 1.23.0`, `SimplePlugin.__init__()` renamed the `client_interceptors` parameter to `interceptors` (unified interceptors API). The `LogfirePlugin` was hard-coded to pass `client_interceptors`, which causes a `TypeError` on the newer SDK.

## Fix

Use `inspect.signature()` to detect which parameter name `SimplePlugin.__init__()` accepts at runtime:
- If `interceptors` is in the signature → use the new parameter name (temporalio >= 1.23.0)
- Otherwise → fall back to `client_interceptors` (temporalio < 1.23.0)

This makes `LogfirePlugin` backward-compatible with both old and new Temporal SDK versions.

## Test

Added `test_logfire_plugin_uses_inspect_for_interceptor_param` which verifies:
- `SimplePlugin.__init__` has one of the expected parameter names
- `LogfirePlugin()` instantiates without error regardless of which param is present

### CODE REVIEW

File: pydantic_ai_slim/pydantic_ai/durable_exec/temporal/_logfire.py [hunk 1]
```diff
@@ -36,10 +37,19 @@ def __init__(self, setup_logfire: Callable[[], Logfire] = _default_setup_logfire
...
+        if 'interceptors' in sig.parameters:
+            super().__init__(  # type: ignore[reportUnknownMemberType]
+                name='LogfirePlugin',
+                interceptors=tracing_interceptors,
+            )
+        else:
+            super().__init__(  # type: ignore[reportUnknownMemberType]
+                name='LogfirePlugin',
+                client_interceptors=tracing_interceptors,
+            )
```
[the remark this answers is not in the document]
Comment (giulio-leone) [reply pydantic_ai_slim/pydantic_ai/durable_exec/temporal/_logfire.py]: Acknowledged — analysis observation. The logfire instrumentation follows the existing pattern used elsewhere in the codebase.

**Comment by giulio-leone** [comment]
All 37 CI checks pass ✅. This fixes a real compat issue with temporalio >= 1.23.0 where the sandbox intercepts . Ready for review when you get a chance! 🙏

**Comment by DouweM** [comment]
We're not interested in bulk AI generated PRs (Giulio submitted 10+ on one go)
