### PR TITLE
fix(anthropic): guard against `message=None` in `_map_usage` on Bedrock streams

### LINKED ISSUE #5774: `_map_usage` crashes on Bedrock streams: `RawMessageStartEvent(message=None)` from type-less chunks
### Initial Checks

- [x] I'm using a recent version of Pydantic AI (1.104.0)
- [x] I've searched the issue tracker (closest: #4491, which introduced the code path involved)

### Description

`_map_usage` in `pydantic_ai/models/anthropic.py` does `message.message.usage` for `BetaRawMessageStartEvent` without guarding `message=None`. On Bedrock (`AsyncAnthropicBedrock` via `AnthropicProvider`), the anthropic SDK's stream decoder drops SSE event types, so Bedrock-only chunks like `amazon-bedrock-invocationMetrics` are constructed (non-validating `construct_type`) as `BetaRawMessageStartEvent(message=None)`. Result: `AttributeError: 'NoneType' object has no attribute 'usage'` and the whole run fails.

This bites in a non-obvious way: non-streaming `model.request()` with high `max_tokens` (>~21.3k) triggers the SDK's "Streaming is required" guard, which pydantic-ai catches (string-matching the error message — the #4491 fix) and falls back to internal streaming. On Anthropic-direct that fallback is fine; on Bedrock it walks into the broken events. So a *non-streaming* Bedrock call crashes intermittently with a streaming-internals error.

### Reproduction (offline; anthropic 0.105.2, pydantic-ai 1.104.0)

```python
from anthropic._models import construct_type
from anthropic.types.beta import BetaRawMessageStreamEvent
from pydantic_ai.models.anthropic import _map_usage

event = construct_type(
    value={"amazon-bedrock-invocationMetrics": {"inputTokenCount": 1}},
    type_=BetaRawMessageStreamEvent,
)
_map_usage(event, "anthropic", "https://example.invalid", "claude-opus-4-8")
# AttributeError: 'NoneType' object has no attribute 'usage'
```

### Suggested fix

Guard `message.message is None` in `_map_usage` (skip/ignore the event for usage purposes) — the SDK hands out contract-violating events on Bedrock, and pydantic-ai is the first consumer to dereference them. I'm also filing the root cause against anthropic-sdk-python (decoder drops event types; non-validating construct yields `message=None`).

### Python, Pydantic AI & LLM client version

Python 3.14, pydantic-ai 1.104.0, anthropic 0.105.2, AsyncAnthropicBedrock via AnthropicProvider

### PR DESCRIPTION
**Pull request by Oxygen56**
## Summary

Fixes an AttributeError crash in `_map_usage` when running on Bedrock (#5774).

### Problem

On Bedrock (`AsyncAnthropicBedrock` via `AnthropicProvider`), the Anthropic SDK's stream decoder drops SSE event types, so Bedrock-only chunks like `amazon-bedrock-invocationMetrics` are constructed (non-validating `construct_type`) as `BetaRawMessageStartEvent(message=None)`.

`_map_usage` unconditionally dereferenced `message.message.usage`, causing:
```
AttributeError: 'NoneType' object has no attribute 'usage'
```

This is particularly insidious because it surfaces on **non-streaming** Bedrock calls that exceed the SDK's max_tokens threshold, triggering the internal streaming fallback introduced in #4491.

### Fix

Guard `message.message is None` in the `BetaRawMessageStartEvent` branch — return the existing usage or an empty `RequestUsage` when the SDK produces contract-violating events on Bedrock.

### Reproduction (before fix)

Closes #5774

### CODE REVIEW

**Comment by dsfaccini** [comment]
David's AICA here: thanks for digging into this @Oxygen56, and apologies it took a beat to get to it.

Two reasons we're going to route #5774 through a different PR rather than land this one:

1. **The `_map_usage` guard alone doesn't stop the crash.** The real Bedrock failure path goes through `AnthropicStreamedResponse._get_event_iterator`, which dereferences the same `message=None` start event again on the next lines — `event.message.id` and `event.message.container`. With only the `_map_usage` guard, `_map_usage` returns cleanly but `self.provider_response_id = event.message.id` still raises `AttributeError: 'NoneType' object has no attribute 'id'`. The issue's reproduction calls `_map_usage` directly so it passes, but the non-streaming `request()` fallback (the `'Streaming is required'` path) iterates the stream and still crashes. A complete fix has to skip the event in the iterator, not just guard `_map_usage`.

2. **This PR bundles two unrelated changes.** The `openai.py` edit (#5757, stray post-done tool-call deltas) and the `models/__init__.py` edit (#5782, `cancel()` flipping `response.state`) aren't part of #5774 and aren't mentioned in the description. Both look worth doing, but each should be its own PR scoped to its issue so they can be reviewed and credited independently.

Closing in favor of a focused #5774 fix with a regression test. Please do re-open the #5757 and #5782 changes as separate PRs — happy to review them there. Thanks again!
